---
Serilog:
  Using:
  - Serilog.Sinks.Console
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Debug
      System: Debug
      Exceptionless.Web.Security.ApiKeyAuthenticationHandler: Warning
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning
  WriteTo:
  - Name: Console
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithThreadId